
services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: creaventure-pgvector
    environment:
      POSTGRES_USER: creaventure
      POSTGRES_PASSWORD: creaventure
      POSTGRES_DB: creaventure
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U creaventure -d creaventure"]
      interval: 5s
      timeout: 5s
      retries: 5

  chatbot:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    container_name: creaventure-chatbot
    ports:
      - "8000:8000"

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: creaventure-ollama
    ports:
      - "11434:11434"